# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gs9NDsSZFOeG37m_DY3MxyxvaVHw65X_

2.HAFTA UYGULAMALAR

Değişken (Tür) Dönüşümü
"""



x= float(x)
print(x)
print(type(x))
x=2

"""Listeler Örnek-1"""

# 3 Elemanı olan bir liste tanımlayın
#ve 2. elemanı "Rize" olan bir çıktı alın.
list1 = [5, "Rize" , 3]
print(list1[1])

"""Range Örnekleri"""

#1-10  Arasında çift olan sayıları ekrana yazma
for a in range(2,11,2): print(a)

#Range Komutu ile 11 ile 111 arasında olan 5'in katlarını yazdıralım.
#Range kullanma örneği for değişken in range (başlangıç,bitiş,artış miktarı) 1 ise yazmaya gerek yok.
for a in range(15,111,5):
  print(a)

"""# BELİRTİLEN İKİ SAYI ARASINDA YER ALAN SAYI MİKTARINI HESAPLAMA"""

i=0
for x in range(1,5):
  i+=1
print(i-1)



"""# 1'DEN BAŞLAYARAK KLAVYEDEN GİRİLEN BİR SAYI MİKTARINA KADAR ARALIKTAKİ SAYILARI YAZDIRALIM"""

top=0
sayi=int(input("Bir sayı giriniz:"))
for i in range(2,sayi):
  top+=1
  #print(i)
print("TOPLAM SAYI MİKTARI",top)

"""For ve Range kullanmadan "1den klavyeden girilen sayıya kadar" olan sayıların toplamını yazdıran program."""

n=int(input("Bir sayı giriniz:"))
top=n*(n+1)//2
print("Sayıların Toplamı:",top)

"""Yuvarlama Örnekleri"""

pi=3.14159
print(round(pi)) #Belirtilen sayının tam kısmını yazar.
print(round(pi,-

"""True False İfade kullanımı örnekleri"""

a=5
b=10
print(a>b)

print(a<11)

print(a==10)

print(b==10)

print(b!=5) #ifade eşit değildir diye tanımlar ve çalışmaya devam eder.

"""Range komutu kullanmadan "Listeye yer alan elemanları ekrana yazdıran" program"""

Liste= [1,2,3,4,5,6,'Rize',8,9]
print(Liste)

for eleman in Liste:
 print(eleman) #Listedeki eleman sayısı kadar döndürme ve elemanları yazdırma

"""# While Döngüsü kullanımı örnekleri"""

x=1
while x<5:
  print("Burak")
  x+=1 #veya x=x+1

""""Girilen sayıdan başlayarak 0'a kadar geriye doğru sayıları yazan" program"""

sayi1=int(input("Sayını Giriniz"))
while sayi1>0:
  print(sayi1)
  sayi1=sayi1-1

"""Klavyeden 5 sayısı girilene kadar "lütfen 5'e basın diyen,5'e basınca da doğru sayı girdiniz." diyip programı sonlandıran python kod"""

sayi=0
while sayi!=5:
  sayi=int(input("Lütfen 5'e tıklayınız"))
print("Doğru sayıyı girdiniz.")

"""Döngü Kesme işlemleri: Break"""

for i in range(1,6):  #Belirtilen veriye ulaştığında döngüyü kesme
  if i==3: break
  print(i)

"""Herhangi bir başlangıç noktası girilen sayıdan sıfıra doğru saydığında en yakın asal sayı görünce duran ve bulduğu asal sayıyı yazdıran programı yazınız"""

def is_prime(num):
    """Verilen sayının asal olup olmadığını kontrol eder."""
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

def nearest_prime_below(n):
    """Girilen sayıdan geriye doğru sayarak en yakın asal sayıyı bulur."""
    for i in range(n, -1, -1):
        if is_prime(i):
            return i
    return None  # Eğer asal sayı bulunamazsa

# Kullanıcıdan giriş al
try:
    number = int(input("Bir sayı girin: "))
    nearest_prime = nearest_prime_below(number)
    if nearest_prime is not None:
        print(f"En yakın asal sayı: {nearest_prime}")
    else:
        print("0 veya daha küçük sayılar için asal sayı bulunamaz.")
except ValueError:
    print("Lütfen geçerli bir tam sayı girin.")

"""Herhangi bir başlangıç noktası girilen sayıdan sıfıra doğru saydığında en yakın asal sayı görünce duran ve bulduğu asal sayıyı yazdıran programı yazınız."""

x=int(input("Lütfen Başlangıç Sayısını Giriniz:"))
for i in range(x,0,-1):
  for j in range(2,i):
    if (1%j==0):
      break
    else:
     print("Girilen sayıya en yakın asal sayı:",i)
     break



"""Toplamda 5 şifre hakkı veren ve yanlış şifre girildiğinde "Lütfen Tekrar Deneyiniz" , doğru şifre girildiğinde "Hoş geldiniz" diyen ve 5. kez yanlış girildiğinde ise "Hakkınız Bitti" diyerek programı sonlandıran python kodu yazınız. Doğru şifre: python"""

sifre="python"
hak=5
while (hak>0):
  girdi=input("Lütfen şifreyi giriniz")
  if (girdi=sifre):
    print("Hoş geldiniz.")
    break
  else:
    print("Lütfen tekrar deneyiniz")
    hak-=1
    print("Kalan Hak sayısı",hak )
    if (hak==0)
    print("Hakkınız Bitti.")

"""## **Fonksiyon Tanımlaması**"""

'''
def değişken:
  işlem
  return değişken
'''

def toplama(topla):

def toplama(s1,s2):
  return s1+s2
print(toplama(4,5))

def carp(s1,s2):
  return s1*s2

carp(1,5)

"""Girilen 2 sayı arasındaki 4 işlemi tel fonksiyon ile kontrol edip ekrana dört işlem sonucu yazdıran program
fonksiyon adı: dortislem
"""

def dortislem(say1,say2):
  print("Sayıların Toplamı: ",say1+say2)
  print("Sayıların Farkı: ",say1-say2)
  print("Sayıların Çarpımı: ",say1*say2)
  print("Sayıların Bölümü: ",say1/say2)

dortislem(4,5)

"""## **HATA** **TÜRLERİ**

1-Kullanıcı(Programcı Hataları-Error)
"""

# print("Selen DEMİRCİ) #SyntaxError Hataları

"""**Hata Kontrol için: Gemini**

**2-Mantık Hataları(Bug)**
"""

say=1
say2=3
toplam=say-say2
print(toplam)

"""**3-İstisnai Hatalar**

Kullanıcı kalıpların dışına çıkılması.
"""



"""# GÜNÜN ÖDEVİ

Kullanıcıdan bir hız değeri alan ve hız değeri 120 üzerinde 4 ceza puanı ve girilen hız 100 ile 120 arasında ise 2 ceza puanı alan ve toplam puanı 6'yı geçerse "Ehliyetinize el konulmuştur." diyen python kodu yazınız.
"""

ceza=0
while (ceza <6):
  hiz=int(input("Hız Değerini Giriniz."))
  if (hiz>120):
    ceza +=4
    print("Ceza Puanınız:",ceza)
  elif(120>hiz>100):
      ceza +=2
      print("Ceza Puanınız:",ceza)
print("Hız Kurallarına uymadığınız için ehliyetinize el konulmuştur.")

"""**ÖRNEK=** 2 Fonksiyon tanımlanmasında "tektoplam()", "çifttoplam" olacak şekilde girilen iki sayı arasındaki sayıların tek ve çift toplamlarını yapan python kodu yazınız.
"Baş,bitiş sayıları dahil değil." Sayılar sabit olsun.
"""

def ciftop(a,b):
toplam=0
for i in range(a,b):
  if (i%2==0):
    top+=i
return print(top)

"""# **KELİME VE CÜMLE HESAPLAMALARI**

split() ve len() komutları ile kelime ve karakter hesaplamaları yapılır
"""

cumle="Ptyhon çok eğlenceli bir derstir."
kelime=cumle.split() #cumleyi ayrı ayrı kelimelerine ayırır.
print(kelime)

cumle2="Selen DEMİRCİ"
result=len(cumle2)
print(result)

"""Kimlik numarası girilen personelin kimlik numarası 11 haneli ise "hoşgeldin" değilse "Hatalı giriş lütfen tekrar deneyin" uyarısı veren python programı"""

kimlikno=input("Kimlik numarasını giriniz.")
if len(kimlikno)==11:
  print("Hoş geldiniz.")
else:
 if len(kimlikno)<=11:
  print("Lütfen tekrar deneyin")

tc=input("TC Numarasını Giriniz.")
while len(tc)!=11:
  tc=input("Hatalı Giriş")
print("Hoşgeldiniz")

"""# Hata kodları örnekleri ve Geri döndürmeler

Pythonda hata kodları için tyr, except ve finally komutları kullanılır. Bu komutların amacı hata ile karşılaştırıldığında kullanıcıya geriye dönük mesajlar vermektir.

**Try** komutları hataları denetler
**except** komutta hata durumunda doğru işlemleri yapar
**finally** ise işlemlere bakmaksızın en son çalıştırılan komuttur.
"""

try:
  sayi1=int(input("Bir sayı giriniz:"))
  sayi2=int(input("Bir sayı giriniz:"))
  sonuc=sayi1/sayi2
  print(sonuc)
except ValueError:
  print("Boş değer girilmez")

"""Girilen bir cümlenin kelime uzunluğunu hesaplayıp kelimeleri diziye atıp fonksiyon ile çağrılma durumunda aralıktaki kelimeleri yazdıran python kod. (baş bit dahil)"""

def toplam(bas,bit)
   bas
cumle=input("Bir cümle giriniz.")
print(len(cumle))
kelime=cumle.split()
print(kelime)



"""# Dizilerde Sıralı İşlemler"""



liste=[1,2,3,4,5]
liste.insert(4,"6")
print(liste)

liste=[1,2,3,4,5]
print(min(liste))

"""# Listelerde sıralama işlemlerimiz"""

liste=[6,88,5,-7,35,3,666]
print(liste)

liste=["f","a","t","b","r"] #Harf veya rakamları kullanış sırasına göre sıralamak.
liste.sort()
print(liste)

"""# Bir alışveriş listesi oluşturmanızı ve yazılımınızda 10 adet ürün eklemeniz gerekmektedir.

"""

1 = elma - 10.0 TL (KDV 8.0%)
2 = ekmek - 5 TL (KDV )
3 = süt
4 = çikolata
5 = peynir
6 = yumurta
7 = makarna
8 = zeytinyağı
9 = şampuan
10 = deterjan

alisveris_listesi = []
for i in range(10):
    urun = input("Almak istediğiniz ürünü giriniz:")
    alisveris_listesi.append(urun)
    print(alisveris_listesi)

urunler = [("elma", 10.0), ("ekmek", 5.0), ("süt", 12.0) ("çikolata",  25.0),("peynir",40.0) ]
urun=input("Bir ürün ismi giriniz")
adet=int(input("Adet giriniz"))

if urun in urunler

   toplam=fiyat*adet
)

!pip install gradio

import gradio as gr

def hesapla(sayi1, sayi2, islem):
    sayi1 = float(sayi1)
    sayi2 = float(sayi2)

    if islem == "top":
        return sayi1 + sayi2
    elif islem == "çık":
        return sayi1 - sayi2
    elif islem == "böl":
        return sayi1 / sayi2 if sayi2 != 0 else "Sıfıra bölme hatası"
    elif islem == "çarp":
        return sayi1 * sayi2

with gr.Blocks() as app:
    gr.Markdown("## Basit Hesap Makinesi")

    sayi1 = gr.Textbox(label="Birinci Sayı")
    sayi2 = gr.Textbox(label="İkinci Sayı")

    islem = gr.Dropdown(label="İşlem Seçin", choices=["top", "çık", "böl", "çarp"])

    hesapla_btn = gr.Button("Hesapla")
    sonuc = gr.Textbox(label="Sonuç", interactive=False)

    hesapla_btn.click(hesapla, inputs=[sayi1, sayi2, islem], outputs=sonuc)

app.launch()